from pathlib import Path
import json
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, PageBreak, Table, TableStyle, Image

ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'docs'/'VibeCoding_EbookShop_Report.pdf'
pdfmetrics.registerFont(TTFont('Thai','C:/Windows/Fonts/tahoma.ttf')); pdfmetrics.registerFont(TTFont('ThaiB','C:/Windows/Fonts/tahomabd.ttf'))
body=ParagraphStyle('b',fontName='Thai',fontSize=10.5,leading=18,wordWrap='CJK',spaceAfter=8)
h1=ParagraphStyle('h1',fontName='ThaiB',fontSize=25,leading=33,textColor=colors.HexColor('#6256d9'),wordWrap='CJK',spaceAfter=18)
h2=ParagraphStyle('h2',fontName='ThaiB',fontSize=15,leading=23,textColor=colors.HexColor('#3f397d'),wordWrap='CJK',spaceAfter=10)
small=ParagraphStyle('s',fontName='Thai',fontSize=8.5,leading=14,wordWrap='CJK')
def P(s,st=body): return Paragraph(s,st)
def foot(c,d):
 c.saveState(); c.setFont('Thai',8); c.setFillColor(colors.HexColor('#77738b')); c.drawString(45,25,'LumiShelf - Vibe Coding E-book 2026'); c.drawRightString(550,25,str(d.page)); c.restoreState()
story=[Spacer(1,70),P('รายงานผลโครงงาน',small),P('LumiShelf<br/>ร้าน E-book พร้อม Android App',h1),P('เว็บสำหรับลูกค้าที่เชื่อม Supabase จริง ทำงานบน Vercel และเปิดผ่าน MIT App Inventor WebViewer'),Spacer(1,18),P('<b>Production</b><br/>https://vibecode-gamma-murex.vercel.app'),P('<b>Source</b><br/>https://github.com/bfirstkok/lumishelf-vibe-ebook-2026'),P('<b>วันที่ตรวจสอบ</b><br/>15 กันยายน 2026'),PageBreak(),P('1. ขอบเขตและหนังสือ',h1),P('ร้านมีหนังสือ 6 เล่ม โดยสามเล่มหลักนำเนื้อหาจากโปรเจกต์ใบงานเดิมมาจัดทำเป็นคู่มือภาพประกอบแบบสไลด์: Media Player PRO, Tarot App และ SQLite Task Manager PRO เล่มละ 6 หน้า อีกสามเล่มเป็นเรื่องสั้นภาพประกอบเล่มละ 4 หน้า'),P('ทุกเล่มเป็น PDF แนวนอน 16:9 มีปก ภาพประกอบ ลำดับเนื้อหา และองค์ประกอบแบบสไลด์ พร้อมหน้ารายละเอียดและ Checkout ในร้าน'),P('เส้นทางผู้ใช้',h2),P('เลือกเล่ม → กรอกชื่อและอีเมล → สร้างหมายเลข LS และออเดอร์ PENDING → กด “จำลองชำระเงินสำเร็จ” ในส่วน DEMO ONLY → PAID → แสดงตัวอย่างอีเมลจำลองสำเร็จและลิงก์ PDF ชั่วคราว'),PageBreak(),P('2. ฐานข้อมูลและความปลอดภัย',h1),P('Supabase เก็บ books และ orders จริง ส่วนไฟล์ PDF อยู่ใน Storage bucket ชื่อ ebooks ซึ่งตั้งเป็น private ตาราง public เปิด RLS ทั้งหมด ผู้ใช้ anon อ่านรายการหนังสือ active ได้ แต่ไม่มีสิทธิ์อ่านหรือเขียน orders'),P('การสร้างออเดอร์ ค้นหา ชำระจำลอง และสร้างลิงก์ดาวน์โหลดทำผ่าน Next.js server routes โดยใช้ secret key ใน Vercel environment เท่านั้น ค่าจากผู้ใช้ถูกตรวจสอบ และราคาอ่านจาก catalog ฝั่ง server'),P('หน้ารายละเอียดออเดอร์ไม่เปิดด้วย UUID อย่างเดียว หลังสร้างหรือค้นหา ระบบออก token แบบสุ่ม เก็บเฉพาะ SHA-256 hash ในฐานข้อมูล และส่ง token ผ่าน HTTP-only Secure cookie การค้นหาต้องใช้หมายเลขออเดอร์กับอีเมลที่ตรงกัน'),P('เมื่อ PAID เซิร์ฟเวอร์สร้าง signed URL อายุ 900 วินาที URL ที่แก้ token ใช้ไม่ได้ และ public storage URL ถูกปฏิเสธ'),PageBreak(),P('3. ผลตรวจ Production',h1)]
results=json.loads((ROOT/'docs'/'production-test-results.json').read_text(encoding='utf-8'))
rows=[[P('รายการ',small),P('ผล',small)]]+[[P(x['name'],small),P('ผ่าน',small)] for x in results['checks']]
t=Table(rows,colWidths=[430,65],repeatRows=1);t.setStyle(TableStyle([('FONTNAME',(0,0),(-1,-1),'Thai'),('BACKGROUND',(0,0),(-1,0),colors.HexColor('#e9e7ff')),('GRID',(0,0),(-1,-1),.35,colors.HexColor('#cbc8dc')),('VALIGN',(0,0),(-1,-1),'TOP'),('LEFTPADDING',(0,0),(-1,-1),7),('RIGHTPADDING',(0,0),(-1,-1),7),('TOPPADDING',(0,0),(-1,-1),5),('BOTTOMPADDING',(0,0),(-1,-1),5)]));story+=[t,P('ผลรวม 15/15 รายการ ผ่านทั้งหมด ใช้ข้อมูลทดสอบ demo@example.com และไม่รับเงินจริง',small),PageBreak(),P('4. Android และไฟล์ส่ง',h1),P('นำเข้า LumiShelf.aia ใน MIT App Inventor และ Build เป็น LumiShelf.apk สำเร็จ แพ็กเกจ appinventor.ai_bfirstkok.LumiShelf, minSdk 14, targetSdk 36 และติดตั้งบน Android Emulator สำเร็จ'),P('Screen1 มี WebViewer เต็มหน้าจอ เปิด Production URL, FollowLinks=true, IgnoreSslErrors=false และ UsesLocation=false บล็อก BackPressed ตรวจ CanGoBack: ถ้าย้อนเว็บได้จะ GoBack มิฉะนั้น closeScreen'),P('การส่งอีเมลใช้ผลจำลองตามเงื่อนไขใบงาน: หน้าจอแสดงผู้รับ หัวข้อ หมายเลขออเดอร์ และสถานะ SIMULATED พร้อมระบุชัดว่าไม่มีอีเมลจริง'),P('ไฟล์สำคัญ',h2),P('ส่งอาจารย์/LumiShelf-Complete-Submission.zip<br/>mobile/LumiShelf.apk<br/>mobile/LumiShelf.aia<br/>docs/VibeCoding_EbookShop_Report.pdf<br/>docs/SUBMISSION_CHECKLIST.md<br/>docs/production-test-results.json'),P('สรุป: ฟังก์ชันหลักครบตามใบงานและตรวจบน Production จริงแล้ว ระบบชำระเงินและอีเมลเป็นการจำลองเพื่อการศึกษาเท่านั้น',h2)]
SimpleDocTemplate(str(OUT),pagesize=A4,rightMargin=45,leftMargin=45,topMargin=48,bottomMargin=45,title='LumiShelf Vibe Coding E-book Report').build(story,onFirstPage=foot,onLaterPages=foot)
print(OUT)
