"use client";
import Link from 'next/link';
import {useEffect,useState} from 'react';
import {Check,Copy,Download,LoaderCircle,MailCheck,PartyPopper,ShieldCheck} from 'lucide-react';
import {getBook,formatBaht} from '@/lib/books';
import type {Order} from '@/lib/orders';
export default function OrderClient({id}:{id:string}){
 const [order,setOrder]=useState<Order|null>(),[error,setError]=useState(''),[busy,setBusy]=useState(false),[copied,setCopied]=useState(false);
 useEffect(()=>{let active=true;fetch('/api/orders/'+id,{cache:'no-store'}).then(async res=>{const data=await res.json();if(active){setOrder(res.ok?data:null);if(!res.ok)setError(data.error);}}).catch(()=>{if(active){setOrder(null);setError('โหลดข้อมูลไม่ได้');}});return()=>{active=false;};},[id]);
 async function run(pay=false){setBusy(true);setError('');try{const res=await fetch('/api/orders/'+id+(pay?'/pay':''),{method:pay?'POST':'GET',cache:'no-store'});const data=await res.json();if(!res.ok)throw Error(data.error);setOrder(data);}catch(e){setError(e instanceof Error?e.message:'ดำเนินการไม่ได้');}finally{setBusy(false);}}
 if(order===undefined)return <section className="state-page"><LoaderCircle className="spin"/><h1>กำลังเปิดคำสั่งซื้อ…</h1></section>;
 if(!order)return <section className="state-page"><h1>กรุณายืนยันคำสั่งซื้อ</h1><p>{error}</p><Link href="/track" className="primary-button">ค้นหาด้วยเลขออเดอร์และอีเมล</Link></section>;
 const book=getBook(order.bookId);if(!book)return null;const paid=order.status==='PAID';
 return <section className="order-page"><div className={'status-orb '+(paid?'paid':'')}>{paid?<PartyPopper/>:<ShieldCheck/>}</div><span className="step">ขั้นตอนที่ 2 จาก 2</span><h1>{paid?'หนังสือพร้อมแล้ว!':'สร้างคำสั่งซื้อแล้ว'}</h1><p>{paid?'ชำระจำลองสำเร็จ ดาวน์โหลด PDF ได้ด้านล่าง':'เก็บหมายเลขคำสั่งซื้อไว้สำหรับติดตามภายหลัง'}</p><div className="receipt"><div className="receipt-head"><span>หมายเลขคำสั่งซื้อ</span><button onClick={async()=>{try{await navigator.clipboard.writeText(order.orderNumber);setCopied(true);}catch{setError('คัดลอกไม่ได้ กรุณาจดหมายเลข');}}}><strong>{order.orderNumber}</strong>{copied?<Check size={16}/>:<Copy size={16}/>}</button></div><div className="receipt-row"><span>หนังสือ</span><strong>{book.title}</strong></div><div className="receipt-row"><span>ผู้สั่งซื้อ</span><strong>{order.customerName}</strong></div><div className="receipt-row"><span>อีเมล</span><strong>{order.customerEmail}</strong></div><div className="receipt-row"><span>ยอดรวม</span><strong>{formatBaht(order.total)}</strong></div><div className="receipt-row"><span>สถานะ</span><span className={'status-pill '+(paid?'paid':'')}>{order.status}</span></div></div>{error&&<p role="alert" className="form-error">{error}</p>}{paid?<div className="paid-actions">{order.downloadUrl?<a className="primary-button wide" href={order.downloadUrl} rel="noreferrer"><Download size={18}/>ดาวน์โหลด PDF ({book.pages} หน้า)</a>:<p role="alert">{order.downloadError}</p>}<p>ลิงก์มีอายุ 15 นาที กดรีเฟรชเพื่อรับลิงก์ใหม่</p><button className="card-button" disabled={busy} onClick={()=>run()}>รีเฟรชลิงก์ดาวน์โหลด</button><div className="email-preview"><MailCheck/><h2>{order.emailStatus==='SIMULATED'?'จำลองส่งอีเมลสำเร็จ':'เตรียมส่งมอบหนังสือ'}</h2><p>โหมดทดสอบตามใบงาน ไม่มีการส่งอีเมลจริง</p><dl><dt>ถึง</dt><dd>{order.customerEmail}</dd><dt>เรื่อง</dt><dd>หนังสือของคุณพร้อมแล้ว — {book.title}</dd></dl><p>คำสั่งซื้อ {order.orderNumber} มีสถานะ PAID</p>{order.downloadUrl&&<a href={order.downloadUrl} rel="noreferrer">เปิดลิงก์ในอีเมลจำลอง (อายุ 15 นาที)</a>}</div>{order.emailStatus!=='SIMULATED'&&<button disabled={busy} onClick={()=>run(true)}>ลองส่งอีเมลจำลองอีกครั้ง</button>}</div>:<div className="payment-panel"><div className="demo-notice"><strong>DEMO ONLY · MOCK PAYMENT</strong><p>ไม่มีการรับเงินจริง ปุ่มนี้บันทึกสถานะ PAID ในฐานข้อมูล</p></div><button className="primary-button wide" onClick={()=>run(true)} disabled={busy}>{busy?'กำลังดำเนินการ…':'จำลองชำระเงินสำเร็จ'}</button></div>}<Link href="/track" className="text-link">ติดตามคำสั่งซื้อ</Link></section>;
}
